### ISSUE TITLE
[Update]: Click on the Add to report button should be Create Report

### ISSUE THREAD

**Issue by akshaymittal143** [googlecodelabs/iot-data-pipeline#12]
In Step: editing field type, after importing bigQuery weatherDataSet table. 
- User should click Create Report button instead of Add Report
- Updated screenshot is below

![datastudio-update](https://user-images.githubusercontent.com/8115184/46577644-fbc1a880-c9b0-11e8-906d-e36509e90372.PNG)

**Comment by akshaymittal143** [comment]
Documentation update: https://codelabs.developers.google.com/codelabs/iot-data-pipeline/index.html?index=..%2F..%2Findex#8

**Comment by sunsetmountain** [comment]
Updated
