### ISSUE TITLE
No handlers could be found for logger "grpc._plugin_wrapping"

### ISSUE THREAD

**Issue by babsuz12** [googlecodelabs/iot-data-pipeline#6]
I am getting the following error:

No handlers could be found for logger "grpc._plugin_wrapping" and the data doesn't get published in the pubsub.

**Comment by azharkhn** [comment]
Are you able to find the solution for this issue @babsuz12 ?

**Comment by cezane** [comment]
I am also getting this error... 

> No handlers could be found for logger "grpc._plugin_wrapping"

**Comment by babsuz12** [comment]
My problem turned out to be Raspberry pie Internet connection

**Comment by dwanderton** [comment]
+1, not resolved by @sunsetmountain suggestion 😔
